# Generated by Django 4.1.2 on 2022-10-24 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('cnpj', models.IntegerField(max_length=20)),
                ('telefone', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prioridade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sistema', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=1000)),
                ('resolução', models.CharField(max_length=1000)),
                ('solicitante', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.funcionario')),
                ('prioridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.prioridade')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.sistema')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.status')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.tipochamado')),
            ],
        ),
    ]
