# Generated by Django 4.1.2 on 2022-10-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='resolução',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
