# Generated by Django 4.1.2 on 2022-10-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_cliente_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='tipo',
            new_name='tipo_chamado',
        ),
    ]
