# Generated by Django 4.1.2 on 2022-11-01 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_alter_chamado_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.prioridade'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='resolucao',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='solicitante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='tipo_chamado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.tipochamado'),
        ),
    ]
