# Generated by Django 4.1.2 on 2022-11-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_alter_chamado_data_alter_chamado_prioridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='titulo',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
