# Generated by Django 4.1.2 on 2022-12-07 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0011_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='tipo_chamado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.tipochamado'),
        ),
    ]
