# Generated by Django 4.1.2 on 2024-04-29 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_alter_chamado_tipo_chamado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='tipo_chamado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.tipochamado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
