# Generated by Django 4.1.2 on 2024-05-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0016_eventocalendario_delete_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocalendario',
            name='data_inicio',
            field=models.DateField(blank=True),
        ),
    ]
